---
name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  core:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    env:
      GOBIN: /home/runner/.local/bin
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        mkdir -p /home/runner/.local/bin
        echo "::add-path::/home/runner/.local/bin"
        mkdir -p .coverage
        echo "*** Current Directory ***"
        pwd
        echo "*** Environment Variables ***"
        env | sort
        echo "*** Executable Path ***"
        echo "$PATH" | tr ':' '\n'
        echo "*** Workspace Files ***"
        find .
        which make
    - name: Install prerequisites
      run: |
        sudo apt-get --assume-yes install make
        sudo apt-get --assume-yes install nftables
        sudo nft --version
        sudo nft -a list ruleset
    - name: Install Go modules
      run: |
        make dep
    - name: Validate prerequisites
      run: |
        echo "*** Local binaries ***"
        find /home/runner/.local/bin
    - name: Run tests
      run: make test
    - name: Generate coverage report
      run: make coverage
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: Upload coverage report
        path: |
          .coverage/**/*.html
          .coverage/**/*.out
